# ===========================
# Vanilla Defaults
# ===========================

theme: dragon-monkey  #comment out to test remote theme
remote_theme: null    #Diffracted84/dragon-monkey

title: "Vanilla Test Site"
description: "Testing Dragon Monkey theme defaults"
